# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone X"
])

languages([
  "en-US"
])

# The name of the scheme which contains the UI Tests
scheme("WishAppUITests")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
launch_arguments(["WISHAPP_TESTING"])

#reinstall_app(true)
#stop_after_first_error(true)
concurrent_simulators(false)

configuration("Debug")

derived_data_path("./fastlane/DerivedData")
